swagger: "2.0"
info:
  description: "机器人接口"
  version: "1.0.0"
  title: "Robot Api"
  contact:
    email: "372290258@qq.com"
host: “robot.weima123.cn”
basePath: "/robot"
tags:
- name: "auth"
  description: "验证接口"
- name: "notify"
  description: "通知信息，用于同步app以及统计"
- name: "base"
  description: "机器人信息"
- name: "common"
  description: "公共接口"
schemes:
- "http"
paths:
  /auth/token:
    post:
      x-swagger-router-controller: "auth"
      tags:
      - "auth"
      summary: "机器人注册"
      description: "注册激活机器人"
      operationId: "registerRobot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "注册信息"
        required: true
        schema:
          $ref: "#/definitions/RegisterRobot"
      responses:
        405:
          description: "Invalid operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Robot"
  /auth/refresh_token:
    post:
      x-swagger-router-controller: "auth"
      tags:
      - "auth"
      summary: "刷新机器人token"
      description: "更新机器人的token"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "刷新信息"
        required: true
        schema:
          $ref: "#/definitions/RefreshRobot"
      responses:
        405:
          description: "Invalid operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Robot"
      security:
      - token: []
  /sound/voice/{voice_id}:
    get:
      x-swagger-router-controller: "sound"
      tags:
      - "sound"
      summary: "获取专辑音频"
      description: "获取专辑音频"
      # operationId: "getVoice"
      produces:
      - "application/json"
      parameters:
      - name: "voice_id"
        in: "path"
        description: "声音id"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SoundVoice"
      security:
      - token: []
  /book/album/{album_id}:
    get:
      x-swagger-router-controller: "book"
      tags:
      - "book"
      summary: "获取绘本"
      description: "获取绘本"
      # operationId: "getVoice"
      produces:
      - "application/json"
      parameters:
      - name: "album_id"
        in: "path"
        description: "绘本id"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BookAblumDetail"
      security:
      - token: []
  /base/night:
    get:
      x-swagger-router-controller: "robot"
      tags:
      - "base"
      summary: "获取机器人夜间模式信息"
      description: "获取机器人夜间模式信息"
      # operationId: "getNight"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RobotNight"
      security:
      - token: []
  /base/anti_addiction:
    get:
      x-swagger-router-controller: "robot"
      tags:
      - "base"
      summary: "获取机器人防沉迷信息"
      description: "获取机器人防沉迷信息"
      # operationId: "getAntiAddiction"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RobotAntiAddiction"
      security:
      - token: []
  /notify/{type}:
    post:
      x-swagger-router-controller: "notify"
      tags:
      - "notify"
      summary: "通知开始做某事"
      description: "通知开始做某事"
      operationId: "start"
      deprecated: true
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "path"
        description: "类型：spell，read"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "启动信息"
        required: true
        schema:
          $ref: "#/definitions/NotifyStart"
      responses:
        405:
          description: "Invalid operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - token: []
    put:
      x-swagger-router-controller: "notify"
      tags:
      - "notify"
      summary: "通知结束做某事"
      description: "通知结束做某事"
      operationId: "end"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "path"
        description: "类型：spell，read"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "结束信息"
        required: true
        schema:
          $ref: "#/definitions/NotifyEnd"
      responses:
        405:
          description: "Invalid operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - token: []
securityDefinitions:
  token:
    type: "apiKey"
    name: "token"
    in: "header"
definitions:
  RegisterRobot:
    type: "object"
    properties:
      code:
        type: "string"
        description: "注册机器码"
  RefreshRobot:
    type: "object"
    properties:
      refresh_token:
        type: "string"
        description: "注册时获取的刷新token"
  RobotNight:
    type: "object"
    properties:
      is_open:
        type: "boolean"
        description: "是否开启夜间模式"
      start_time:
        type: "string"
        description: "启动时间"
      end_time:
        type: "string"
        description: "结束时间"
  RobotAntiAddiction:
    type: "object"
    properties:
      is_open:
        type: "boolean"
        description: "是否开启防沉迷"
      duration:
        type: "integer"
        description: "时间周期"
  SoundVoice:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      duration:
        type: "integer"
        description: "时长，单位秒"
      attach:
        type: "string"
        description: "附件：音频地址"
  BookAblumDetail:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      cover:
        type: "string"
      author:
        type: "string"
      number:
        type: "string"
        description: "书号"
      contents:
        type: "array"
        items:
          $ref: "#/definitions/BookContent"
  BookContent:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      duration:
        type: "integer"
        description: "时长，单位秒"
      attach:
        type: "string"
        description: "附件：音频地址"
      image:
        type: "string"
      page:
        type: "integer"
        description: "页数"
  NotifyStart:
    type: "object"
    properties:
      module:
        type: "string"
        description: "模块：letter，word，book_album，sound_voice"
      module_id:
        type: "integer"
        description: "对应的id"
  NotifyEnd:
    type: "object"
    properties:
      module:
        type: "string"
        description: "模块：letter，word，book_album，sound_voice"
      module_id:
        type: "integer"
        description: "对应的id"
      duration:
        type: "integer"
        description: "时长：单位秒"
      percent:
        type: "integer"
        description: "百分比计数：正确率，整数即可"
  Robot:
    type: "object"
    properties:
      token:
        type: "string"
        description: "授权token"
      expire_time:
        type: "string"
        description: "有效期，UTC格式"
      refresh_token:
        type: "string"
        description: "刷新token"
      mqtt_username:
        type: "string"
        description: "mqtt服务器的账号"
      mqtt_password:
        type: "string"
        description: "mqtt服务器的密码"
  IdResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      result:
        type: "object"
        properties:
          id:
            type: "integer"
            description: "id"
  ApiResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"
  